### ISSUE TITLE
대규모 트래픽을 고려한 코드 리팩토링

### ISSUE THREAD

**Issue by lmw7414** [lmw7414/simple-sns#13]
앞서 프로젝트를 진행하며 다음과 같은 문제점들을 떠올렸다
### TODO
---
* [x] #14
* [x] 문제점2. 매 API 요청시마다 조회하는 User
* [x] 문제점3. Alarm까지 생성해야 응답을 하는 API
* [x] #16
* [x] 문제점5. 데이터베이스로 날라가는 Query들은 최적화가 되었을까?

위의 문제를 해결하기 위한 코드 리팩토링 및 새로운 기술(Redis, Kafka 등) 도입을 고려해볼 생각이다.
